project_name: turbogit

before:
  hooks:
    - go mod download

builds:
  - <<: &build_defaults
      binary: bin/tug
      ldflags:
        - -s -w
        - -X github.com/b4nst/turbogit/cmd.Version={{.Version}}
        - -X github.com/b4nst/turbogit/cmd.Commit={{.ShortCommit}}
        - -X github.com/b4nst/turbogit/cmd.BuildDate={{.Date}}
    id: macos
    goos: [darwin]
    goarch: [amd64]

  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [386, amd64, arm64]

  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [386, amd64]
    
archives:
  - id: nix
    builds: [macos, linux]
    <<: &archive_defaults
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    replacements:
      darwin: macOS
    format: tar.gz
    files:
      - LICENSE
      - ./config/tug.toml
  - id: windows
    builds: [windows]
    <<: *archive_defaults
    wrap_in_directory: false
    format: zip
    files:
      - LICENSE
      - ./config/tug.toml

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^build:"

release:
  github:
  prerelease: auto

brews:
  - # IDs of the archives to use.
    ids: [nix]
    # Github repository to push the tap to.
    github:
      owner: b4nst
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/b4nst/turbogit"
    description: "Cli tool built to help you deal with your day-to-day git work."
    skip_upload: auto
    # Custom block for brew.
    # Used to specify alternate downloads for devel or head releases.
    custom_block: |
      head do
        url "https://github.com/b4nst/turbogit.git"
        depends_on "go"
      end
    test: |
      help_text = shell_output("#{bin}/tug --help")
      assert_includes help_text, "Usage:"

    # Custom install script for brew.
    # Default is 'bin.install "program"'.
    install: |
      bin.install "bin/tug"
      etc.install "config/tug.toml"
      (bash_completion/"tug.sh").write `#{bin}/tug completion bash`
      (zsh_completion/"_tug").write `#{bin}/tug completion zsh`
      (fish_completion/"tug.fish").write `#{bin}/tug completion fish`

nfpms:
  - license: MIT
    maintainer: banst
    homepage: https://github.com/b4nst/turbogit
    bindir: /usr/local
    dependencies:
      - git
    formats:
      - deb
      - rpm
    config_files:
      "./config/tug.toml": "$HOME/.config/tug/tug.toml"

scoop:
  bucket:
    owner: b4nst
    name: scoop-bucket
  homepage: https://github.com/b4nst/turbogit
  skip_upload: auto
  description: "Cli tool built to help you deal with your day-to-day git work."
  license: MIT